# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Gjs Types All

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x]
        architecture:
          - x64
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn run build
    - run: yarn run build:types:gjs
    - run: NODE_OPTIONS=--max_old_space_size=9216 yarn run validate:types:gjs
    # Ava test needs a refactoring
    # - run: yarn run test:ava