# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        architecture:
          - x64
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt-get update
    - name: Install dependencies for regress test
      run: sudo apt-get --yes install libappindicator3-dev libgda-5.0-dev libgirepository1.0-dev libgtk-3-dev libgtksourceview-3.0-dev libnotify-dev libsoup2.4-dev libwebkit2gtk-4.0-dev
    - run: npm install
    - run: npm run regress
    - run: npm run test:ava
    - run: npm run build:types:gjs
    - run: npm run build:types:node
    - run: npm run build
    - run: npm run build:examples:gjs
    # TODO fix build node-gtk on Github actions
    # - name: Install dependencies for node-gtk
    #   run: sudo apt-get --yes install build-essential gobject-introspection libgirepository1.0-dev libcairo2 libcairo2-dev
    # - run: npm run install:examples:node
    # - run: npm run build:examples:node